services:
  - type: web
    name: ethic-platform
    env: node
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: NPM_CONFIG_PRODUCTION
        value: false