name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use Node 18 which has better crypto support
          
      - name: Install dependencies
        run: npm install
        
      - name: Install client dependencies & Build
        run: |
          cd client
          npm install
          NODE_OPTIONS=--openssl-legacy-provider npm run build
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/dist
